spring:
  application:
    name: Fourj
server:
  port: 8080

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 15s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 50
    instances:
      externalServiceCB:
        base-config: default


logging:
  level:
    com.Resilience4.Fourj: DEBUG
    io.github.resilience4j: INFO